-- --------------------------------------------------------
-- Supabase Database Schema for 'Memories AI'
-- --------------------------------------------------------

-- Custom Types Overview (Used in columns below):
-- ENUM visibility_level: 'private', 'shared', 'public'
-- ENUM gender_id: 'male', 'female', 'nonbinary', 'unspecified'
-- ENUM age_band: 'child', 'teen', 'young_adult', 'adult', 'senior', 'unspecified'
-- ENUM role_type: 'admin', 'regular_user'

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    name text,
    lastname text,
    role role_type DEFAULT 'regular_user'::role_type,
    email text UNIQUE,
    avatar_url text,
    preferred_language text DEFAULT 'es'::text,
    timezone text DEFAULT 'America/Lima'::text,
    terms_accepted_at timestamp with time zone,
    last_login_at timestamp with time zone
);

CREATE TABLE public.user_preferences (
    user_id uuid PRIMARY KEY REFERENCES public.users(id),
    receive_notifications boolean DEFAULT true,
    theme_mode text DEFAULT 'dark'::text,
    ai_default_model text
);

CREATE TABLE public.user_devices (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES public.users(id),
    device_token text UNIQUE,
    device_os text,
    device_model text,
    is_active boolean DEFAULT true,
    last_activity_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.people (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    owner_user_id uuid REFERENCES public.users(id),
    display_name text,
    alias text,
    gender gender_id DEFAULT 'unspecified'::gender_id,
    age_range age_band DEFAULT 'unspecified'::age_band,
    height_cm numeric,
    traits jsonb DEFAULT '{}'::jsonb,
    consent_generate boolean DEFAULT true,
    visibility text DEFAULT 'private'::text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    is_self boolean DEFAULT false
);

CREATE TABLE public.person_reference_image (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    person_id uuid REFERENCES public.people(id),
    storage_path text,
    caption text,
    is_primary boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.person_insights (
    person_id uuid PRIMARY KEY REFERENCES public.people(id),
    user_id uuid REFERENCES public.users(id),
    summary text,
    dominant_role text,
    dominant_role_confidence numeric,
    emotional_impact jsonb,
    relationship_evolution jsonb,
    key_themes text[],
    representative_quotes text[],
    risk_flags jsonb,
    confidence_score numeric,
    source_memories_count integer,
    analyzed_at timestamp with time zone DEFAULT now(),
    model_used text,
    input_hash text
);

CREATE TABLE public.memories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    content text,
    ai_image text, -- Imagen generada por la IA basada en Ghibli
    ai_title text, -- Título resumido
    ai_feelings text[],
    ai_representative_moments text[],
    ai_image_prompt text,
    ai_people text[],
    ai_people_roles jsonb,
    ai_places text[],
    ai_objects text[],
    ai_actions text[],
    ai_temporal_context text,
    ai_overall_tone text,
    ai_category text[],
    ai_key_topics text[],
    ai_highlighted_quote text,
    ai_sensorial_elements jsonb[],
    ai_lessons_learned text[],
    ai_emotional_intensity bigint,
    ai_event_duration text,
    normalized_date text,
    ai_main_representative_moment text,
    embedding halfvec, -- extension vector/halfvec required
    isTruthful boolean DEFAULT false,
    is_enable boolean DEFAULT true,
    user_id uuid REFERENCES public.users(id),
    visibility visibility_level DEFAULT 'private'::visibility_level
);

CREATE TABLE public.memory_notes (
    id bigint PRIMARY KEY, -- Default uses sequence 'memory_notes_id_seq'
    memory_id bigint REFERENCES public.memories(id),
    created_at timestamp with time zone DEFAULT now(),
    content text,
    author_type text DEFAULT 'user'::text CHECK (author_type IN ('user', 'assistant'))
);

CREATE TABLE public.memory_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    memory_id bigint REFERENCES public.memories(id),
    question text,
    answered boolean DEFAULT false,
    user_answer text,
    ai_model text DEFAULT 'gpt-4o-mini'::text,
    version integer DEFAULT 1
);

CREATE TABLE public.memory_person (
    memory_id bigint REFERENCES public.memories(id),
    person_id uuid REFERENCES public.people(id),
    role text,
    PRIMARY KEY (memory_id, person_id)
);

CREATE TABLE public.memory_relationships (
    memory_id_a bigint REFERENCES public.memories(id),
    memory_id_b bigint REFERENCES public.memories(id),
    relationship_type text,
    created_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (memory_id_a, memory_id_b)
);

CREATE TABLE public.chats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid REFERENCES public.users(id),
    title text,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    chat_id bigint REFERENCES public.chats(id),
    sender_type text CHECK (sender_type IN ('user', 'ai')),
    content text,
    metadata jsonb
);

CREATE TABLE public.ai_usage_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid REFERENCES public.users(id),
    memory_id bigint REFERENCES public.memories(id),
    api_service text,
    model_used text,
    input_tokens integer,
    output_tokens integer,
    estimated_cost numeric,
    success boolean DEFAULT true
);
